"""Optional Google AI Studio TTS for AshenToons.

SECURITY: API key stored locally at the Flow MCP compatible path, never in
request URLs/logs/CLI arguments. Each output is SHA addressed and immutable.
No text, panel or story generated by this adapter; only user-authored lines.
Separate optional external service: charges/quotas depend on Google API project.
"""
from __future__ import annotations

import base64
from hashlib import sha256
import json
import os
from pathlib import Path
import re
import struct
import tempfile
import time
from typing import Callable
import urllib.error
import urllib.request
import wave

from .core import file_hash

GOOGLE_MODEL = "gemini-2.5-flash-preview-tts"
SUPPORTED_GOOGLE_MODELS = frozenset({
    GOOGLE_MODEL,
    "gemini-3.1-flash-tts-preview",
    "gemini-3.8-flash-lite-tts",
})
GOOGLE_VOICES = frozenset({
    "Zephyr", "Puck", "Charon", "Kore", "Fenrir", "Leda",
    "Orus", "Aoede", "Callirrhoe", "Autonoe", "Enceladus",
    "Iapetus", "Umbriel", "Algieba", "Despina", "Erinome",
    "Algenib", "Rasalgethi", "Laomedeia", "Achernar",
    "Alnilam", "Schedar", "Gacrux", "Pulcherrima",
    "Achird", "Zubenelgenubi", "Vindemiatrix",
    "Sadachbia", "Sadaltager", "Sulafat",
})
# Google speaker labels have NO automatic equivalence to Kokoro labels.
DEFAULT_GOOGLE_CAST = {
    "MC": "Gacrux", "Usato": "Puck", "Rose": "Kore",
    "Suzune": "Zephyr", "Kazuki": "Charon",
}
DEFAULT_KOKORO_CAST = {
    "MC": "am_fenrir", "Usato": "am_puck",
    "Rose": "af_bella", "Suzune": "af_heart",
    "Kazuki": "am_michael",
}
MAX_TEXT_CHARS = 400
MAX_AUDIO_SECONDS = 30.0
SAMPLE_RATE = 24000
_API_ROOT = "https://generativelanguage.googleapis.com/v1beta"
FLOW_KEY = Path.home() / ".flow-mcp" / "gemini-key"


def _plausible_key(value: str) -> bool:
    """Permit provider-issued opaque keys without guessing their prefix.

    Reject whitespace, controls, delimiters and unreasonably long values.
    Google is the authority on validity, via the read-only models endpoint.
    """
    return isinstance(value, str) and re.fullmatch(r"[A-Za-z0-9_.-]{20,256}", value) is not None


def credential_ready() -> bool:
    """Status only; never return or log the key."""
    return bool(_load_key())


def _load_key() -> str | None:
    candidate = os.environ.get("GEMINI_API_KEY", "").strip()
    if not candidate and FLOW_KEY.is_file():
        try:
            candidate = FLOW_KEY.read_text(encoding="utf-8").strip()
        except OSError:
            return None
    return candidate if _plausible_key(candidate) else None


def validate_key(key: str, opener=None, timeout: int = 12) -> tuple[bool, str]:
    """Read-only model listing; no speech generation and no Flow credits."""
    if not isinstance(key, str) or not _plausible_key(key.strip()):
        return False, "Invalid API key format"
    fn = opener or urllib.request.urlopen
    req = urllib.request.Request(
        f"{_API_ROOT}/models?pageSize=1",
        headers={"x-goog-api-key": key.strip(), "Accept": "application/json"},
        method="GET")
    try:
        with fn(req, timeout=timeout) as res:
            if res.status != 200:
                return False, f"Google responded HTTP {res.status}"
            response = json.load(res)
            if not isinstance(response, dict) or not isinstance(response.get("models"), list):
                return False, "Unexpected Google key-validation response"
        return True, "Validated against the Google model listing"
    except urllib.error.HTTPError as exc:
        return False, f"Google rejected key validation (HTTP {exc.code})"
    except (urllib.error.URLError, TimeoutError, OSError, ValueError):
        return False, "Could not verify key with Google; check network"
    # Deliberately never print or return the key.


def save_key_securely(key: str, opener=None) -> dict:
    """Verify first, then write to Flow MCP compatible key file with restricted ACL."""
    key = key.strip() if isinstance(key, str) else ""
    valid, note = validate_key(key, opener=opener)
    if not valid:
        return {"status": "FAIL", "message": note}
    folder = FLOW_KEY.parent
    folder.mkdir(parents=True, exist_ok=True)
    if FLOW_KEY.is_symlink():
        return {"status": "FAIL", "message": "Refusing symlink credentials file"}
    # Atomic replace, no secrets in process arguments or printed output.
    descriptor, temporary = tempfile.mkstemp(prefix=".google-key-", dir=folder)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as f:
            f.write(key)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(temporary, 0o600)
        if os.name == "nt":
            import getpass
            import subprocess
            account = getpass.getuser()
            # icacls receives a path and account ONLY; no key in argv.
            result = subprocess.run(
                ["icacls", temporary, "/inheritance:r", "/grant:r", account + ":F"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                check=False, timeout=12)
            if result.returncode != 0:
                return {"status": "FAIL", "message": "Could not restrict key file permissions"}
        os.replace(temporary, FLOW_KEY)
        os.chmod(FLOW_KEY, 0o600)
        return {"status": "PASS", "message": "Google API key validated and stored on this PC", "credential_path": str(FLOW_KEY)}
    except (OSError, RuntimeError, TimeoutError, ValueError):
        return {"status": "FAIL", "message": "Unable to safely save API key"}
    finally:
        try: os.unlink(temporary)
        except OSError: pass


def probe_wave(path: Path) -> dict:
    try:
        if path.is_symlink() or not path.is_file():
            return {"status": "FAIL", "reason": "Unsafe/missing audio"}
        with wave.open(str(path), "rb") as file:
            sample_rate = file.getframerate()
            channels = file.getnchannels()
            bits = file.getsampwidth() * 8
            frames = file.getnframes()
            sample = file.readframes(frames)
        duration = frames / sample_rate
        if (sample_rate != SAMPLE_RATE or channels != 1 or bits != 16 or
                not 0.08 <= duration <= MAX_AUDIO_SECONDS):
            return {"status": "FAIL", "reason": "Invalid WAV metadata"}
        if not sample or max(sample) == min(sample) == 0:
            return {"status": "FAIL", "reason": "Empty or silent waveform"}
        return {"status": "PASS", "duration": round(duration, 3),
                "sha256": file_hash(path), "sample_rate": sample_rate}
    except (OSError, EOFError, ValueError, ZeroDivisionError, wave.Error):
        return {"status": "FAIL", "reason": "Unreadable WAV file"}


def _pcm_from_response(data: dict) -> bytes:
    candidates = data.get("candidates", [])
    if not isinstance(candidates, list):
        raise ValueError("Google did not return audio candidates")
    for candidate in candidates:
        if not isinstance(candidate, dict):
            continue
        for part in (candidate.get("content", {}) or {}).get("parts", []):
            inline = part.get("inlineData") if isinstance(part, dict) else None
            if not isinstance(inline, dict) or not inline.get("data"):
                continue
            mime = inline.get("mimeType", "")
            if not isinstance(mime, str) or "audio/" not in mime:
                continue
            rate = re.search(r"rate=(\d+)", mime)
            if rate and int(rate.group(1)) != SAMPLE_RATE:
                raise ValueError("Unsupported audio sample rate in Google response")
            audio = base64.b64decode(inline["data"], validate=True)
            if not 3840 <= len(audio) <= int(SAMPLE_RATE*2*MAX_AUDIO_SECONDS):
                raise ValueError("Unexpected Google audio duration")
            if len(audio) % 2:
                raise ValueError("Malformed 16-bit PCM audio")
            return audio
    raise ValueError("Google response contained no PCM audio")


def synthesize_google(
    text: str, output: Path, *, voice: str = "Gacrux",
    model: str = GOOGLE_MODEL, style: str = "speak naturally, with clear cinematic storytelling",
    opener=None, retries: int = 2, sleep: Callable[[float], None] = time.sleep,
    api_key: str | None = None,
) -> dict:
    """Generate and atomically write one <=400 character / <=30s WAV segment.

    No paid request is made if a valid destination WAV already exists.
    All Google errors are reduced to status codes, never response bodies.
    """
    if not isinstance(text, str) or not 1 <= len(text.strip()) <= MAX_TEXT_CHARS:
        return {"status": "FAIL", "errors": [f"Text must be 1–{MAX_TEXT_CHARS} characters"]}
    if not isinstance(voice, str) or voice not in GOOGLE_VOICES:
        return {"status": "FAIL", "errors": ["Unsupported Google speaker"]}
    if model not in SUPPORTED_GOOGLE_MODELS:
        return {"status": "FAIL", "errors": ["Google model not in studio allowlist"]}
    if not isinstance(style, str) or len(style) > 180:
        return {"status": "FAIL", "errors": ["Invalid speech direction"]}
    if not isinstance(output, Path) or output.suffix.lower() != ".wav" or output.is_symlink():
        return {"status": "FAIL", "errors": ["Output must be a safe WAV filename"]}
    if output.exists():
        result=probe_wave(output)
        if result["status"] == "PASS":
            return {"status": "PASS", "reused": True, "path": str(output),
                    "voice": voice, "model": model, **result}
        return {"status": "FAIL", "errors": ["Existing WAV invalid; refusing overwrite"]}
    key = api_key if api_key is not None else _load_key()
    if not key:
        return {"status": "BLOCKED", "errors": ["Google API key not configured on this computer"]}
    if not _plausible_key(key):
        return {"status": "BLOCKED", "errors": ["Invalid locally configured Google API key"]}
    fn = opener or urllib.request.urlopen
    req=urllib.request.Request(
        f"{_API_ROOT}/models/{model}:generateContent",
        data=json.dumps({
            "contents": [{"parts": [{"text": "Say " + style + ": " + text.strip()}]}],
            "generationConfig": {
                "responseModalities": ["AUDIO"],
                "speechConfig": {"voiceConfig": {"prebuiltVoiceConfig": {"voiceName": voice}}},
            },
        }).encode("utf-8"),
        headers={"x-goog-api-key": key, "Content-Type": "application/json"},
        method="POST")
    pcm=None
    attempts=max(1,min(1+int(retries),4))
    for attempt in range(attempts):
        try:
            with fn(req, timeout=65) as response:
                if response.status!=200: raise ValueError("Unexpected non-success response")
                data=json.load(response)
            pcm=_pcm_from_response(data)
            break
        except urllib.error.HTTPError as exc:
            if exc.code in (401,403):
                return {"status":"FAIL","errors":[f"Google permission error (HTTP {exc.code}); check key/project"]}
            if exc.code in (400,404):
                return {"status":"FAIL","errors":[f"Google model request rejected (HTTP {exc.code})"]}
            if exc.code in (429,500,502,503,504) and attempt+1<attempts:
                sleep(min(20, 1.5*(2**attempt)))
                continue
            return {"status":"FAIL","errors":[f"Google service unavailable or quota reached (HTTP {exc.code})"]}
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            if attempt+1<attempts:
                sleep(min(20, 1.5*(2**attempt)))
                continue
            return {"status":"FAIL","errors":["Google request failed after bounded retries"]}
        except (ValueError, KeyError, TypeError, base64.binascii.Error) as exc:
            return {"status":"FAIL","errors":["Invalid audio API response: " + type(exc).__name__]}
    if pcm is None:
        return {"status": "FAIL", "errors": ["No valid audio received"]}
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp=None
    try:
        fd,name=tempfile.mkstemp(prefix=".google-tts-", suffix=".wav",dir=output.parent)
        os.close(fd)
        tmp=Path(name)
        with wave.open(str(tmp),"wb") as file:
            file.setnchannels(1)
            file.setsampwidth(2)
            file.setframerate(SAMPLE_RATE)
            file.writeframes(pcm)
        checked=probe_wave(tmp)
        if checked["status"]!="PASS":
            return {"status":"FAIL","errors":["Google generated invalid or silent audio"]}
        if output.exists() or output.is_symlink():
            return {"status":"FAIL","errors":["WAV destination appeared during generation; refusing overwrite"]}
        os.replace(tmp, output)
        return {"status":"PASS","reused":False,"path":str(output),
                "voice":voice,"model":model,"duration":checked["duration"],
                "sha256":file_hash(output),"sample_rate":SAMPLE_RATE,
                "note":"Audio synthesized; requires human speech and scene review"}
    except (OSError,ValueError) as exc:
        return {"status":"FAIL","errors":["Could not save WAV: "+type(exc).__name__]}
    finally:
        if tmp is not None:tmp.unlink(missing_ok=True)


def line_cache_path(folder: Path, text: str, voice: str, style: str,
                    model: str = GOOGLE_MODEL) -> Path:
    digest=sha256(("gtts-v1|"+model+"|"+voice+"|"+style+"|"+text.strip()).encode("utf-8")).hexdigest()[:32]
    return folder / ("gemini-"+digest+".wav")


def synthesize_with_fallback(text: str, folder: Path, *,
                             google_voice: str, kokoro_voice: str,
                             style: str = "cinematic and natural",
                             allow_kokoro_fallback: bool = True,
                             **google_kwargs) -> dict:
    """Google only when locally configured; non-destructively fallback on errors.

    Keeps a separate engine label and speaker ID so cache voice never aliases.
    """
    target=line_cache_path(folder,text,google_voice,style)
    if credential_ready() or google_kwargs.get("api_key"):
        result=synthesize_google(text,target,voice=google_voice,style=style,**google_kwargs)
        if result["status"]=="PASS":
            return {"engine":"google",**result}
        error=result.get("errors",["Google synthesis failed"])
    else:
        error=["Google API key not configured"]
    if not allow_kokoro_fallback:
        return {"status":"BLOCKED","engine":"google","errors":error}
    from .tts import synthesize
    kd=sha256(("kokoro-fallback-v1|"+kokoro_voice+"|"+text.strip()).encode("utf8")).hexdigest()[:32]
    final=folder/("kokoro-"+kd+".wav")
    if final.exists():
        probe=probe_wave(final)
        if probe["status"]=="PASS":
            return {"status":"PASS","engine":"kokoro","reused":True,"path":str(final),
                    "duration":probe["duration"],"voice":kokoro_voice}
        return {"status":"FAIL","errors":["Kokoro fallback output is corrupt; not replacing"]}
    local=synthesize(text,final,voice=kokoro_voice)
    if local["status"]=="PASS":
        return {"engine":"kokoro","reused":False,**local,
                "note":"Google unavailable; original Kokoro voice used"}
    return {"status":"FAIL","errors":["Google failed and Kokoro fallback unavailable"],
            "google_status":error,"kokoro_status":local.get("errors")}
